### ISSUE TITLE
java.lang.NullPointerException at ua.coins.persistence.impl.social.SocialNetManagerImpl

### ISSUE THREAD

**Issue by dpavlikovskiy** [pavlikovskiy/coinshome.net#49]
java.lang.NullPointerException at ua.coins.persistence.impl.social.SocialNetManagerImpl.fireEventCoinGroupUpdateEdit(SocialNetManagerImpl.java:224) at ua.coins.persistence.impl.CoinManagerImpl.approveChanges(CoinManagerImpl.java:747) at ua

**Comment by pavlikovskiy** [comment]
done
